### ISSUE TITLE
What is the `tT_loss`?

### ISSUE THREAD

**Issue by yjc4** [Shark-NLP/DiffuSeq#16]
There is a `tT_loss` term in the final loss: 

https://github.com/Shark-NLP/DiffuSeq/blob/901f8604d619c1923d69e57bd11894523309aab8/diffuseq/gaussian_diffusion.py#L629-L630

What is this? I cannot find it in the paper. And accroding to the code, the `out_mean` looks like the mean value of $x_T\sim\mathcal{N}(0, I)$ as $T\rightarrow +\infty$ from the diffusion forward procedure, and `out_mean ** 2` should then be $\bar{\alpha}_T x_0\rightarrow 0$. Also, there seems no learnable params in the compute graph of `tT_loss`?

I wonder what is this term for, what is the meaning, and where it comes from?

**Comment by yjc4** [comment]
Never mind. Found in (17):

![image](https://user-images.githubusercontent.com/119409808/206611467-f1483b72-8b6d-4d84-9a82-ab3524bd98c0.png)

**Comment by ccchobits** [comment]
Hi, I am still confused about the questions that @yjc4 had mentioned.

As for the previous comment from @yjc4, I think this term couldn't explain these issues, because obviously it has been dropped from step 1 to step 2 in equation (17) from the paper. So could you please clarify them? Thanks.
