### ISSUE TITLE
Modifications for unconditional text generation

### ISSUE THREAD

**Issue by leekum2018** [Shark-NLP/DiffuSeq#20]
Thank you for your meaningful work and nice codes.  Now I would like to seek some help from you. I plan to conduct some experiment for unconditional text generation using your code, in which there is no source sequence for input.  Could you please give me some tips about how and where I should make some modifications. Thanks!

**Comment by summmeer** [comment]
Hi,
You are free to customize the `text_datasets.py` on your own.
