### ISSUE TITLE
About the usage of `batch` in dataset (form of `batch`, `cond`)

### ISSUE THREAD

**Issue by kdha0727** [Shark-NLP/DiffuSeq#34]
It seems that the `batch` argument, which is the first argument of batch (form of `batch`, `cond`), is not used in training and sampling. It is output of TextDataset.model_emb(input_ids) and in TrainLoop class, it is subscripted to `micro`, and used in `SpacedDistribution.training_losses_seq2seq` method. However, in that method, it is saved as `x_start_fix` and never used.
Originally, what is the usage of `batch` argument in dataset?

**Comment by summmeer** [comment]
Yes, we didn't use `batch`, but use `input_ids` to get the vector of `x`. `x_start_fix` is not used in DiffuSeq, but it can be used as a fixed vector if you like. (We use it when we do ablation study)

**Comment by kdha0727** [comment]
I see. Thank you!
