### ISSUE TITLE
Problems about running code.

### ISSUE THREAD

**Issue by yanglilian** [Shark-NLP/DiffuSeq#4]
Thanks for your great work! When I run this command "python -m torch.distributed.launch --nproc_per_node
=7 --master_port=12233 --use_env run_train.py --diff_steps 2000 --lr 0.0001 --learning_steps 140000 --save_interval 20000 --seed 102 --noise_schedule sqrt --h
idden_dim 128 --bsz 2048 --microbatch 64 --dataset dialogue --data_dir datasets/CommonsenseConversation  --vocab b
ert --seq_len 128 --schedule_sampler lossaware --notes dialogue "

The output is stuck with "### Training...", and there is no further log and there are also no logs on wandb, please tell me what to do with that.

**Comment by minghao-wu** [comment]
The code runs smoothly on my side. However, it's computationally expensive.

I quickly run the QQP experiment using the suggested command from the authors. On my under-optimized cluster, it takes around 12 seconds for one iteration on 2 A100 GPUs. 

Suppose you set up the virtual environment correctly, I guess that, you either need to reset `--nproc_per_node` to be the number of GPUs on your machine, or just more patience. LOL.

**Comment by yjc4** [comment]
see #12

**Comment by bc-li** [comment]
I cloned the latest version of code and the problem seems to persist(the log stuck with `"### Training..."`) when I did not set the correct `--nproc_per_node` to be the number of GPUs in my machine. Setting the correct `--nproc_per_node` resolves the problem.
