### ISSUE TITLE
Typo? train.py 

### ISSUE THREAD

**Issue by golankai** [Shark-NLP/DiffuSeq#47]
Hello, I might be horribly mistaken but I also might have seen a "typo".
In train.py first docstring, it says "_Train a diffusion model on **images**_."
Is it incorrect?

![image](https://user-images.githubusercontent.com/72255040/236403282-350bfd6f-0ba3-47b6-82cb-0874e29216e3.png)

**Comment by summmeer** [comment]
It's a typo. The code is inherited from image diffusion models.
