### ISSUE TITLE
Decoding only [UNK] token ?

### ISSUE THREAD

**Issue by cankobanz** [Shark-NLP/DiffuSeq#48]
Hi, 
I try to use DIFFUSEQ to adapt a different language. However, after training with this new language, model continuously produce [UNK] token. 

What could be the reason? Where did I do wrong? Do you have any idea about the problem? Did you something similar experience during development phase?

![image](https://github.com/Shark-NLP/DiffuSeq/assets/81170575/72edfb60-30e3-40df-b0d8-35c06cf57302)

Kind regards.

**Comment by summmeer** [comment]
Hi,
According to our own experience, this may attribute to the insufficient training. Maybe you can train the data using more steps.
