### ISSUE TITLE
RoFormer model instead of BERT?

### ISSUE THREAD

**Issue by mainpyp** [Shark-NLP/DiffuSeq#51]
Hi there, 
have you tried to use the [Roformer model](https://huggingface.co/docs/transformers/model_doc/roformer) for text generation? I want to use that, since it allows the capturing of relative positions of each word.
If you have tried it, do i have to change anything other than just loading the different model because right now, my generation is way worse than BERT what is counterintuitive! :)

**Comment by mainpyp** [comment]
Just replaced the BERT with Roformer config and it worked. Had an additional Position Embedding that messed with the training in the first place!

**Comment by xxiutong** [comment]
have you tried on the baselines? How's the results?
