### ISSUE TITLE
Pretrain DiffuSeq?

### ISSUE THREAD

**Issue by jzhang38** [Shark-NLP/DiffuSeq#6]
Hi,

Thanks for your wonderful work!

To pretrain DiffuSeq on large unsupervised corpus is the first thing that comes in to my mind after reading this paper, since this is what all LM do nowadays. The Commonsense Conversation dataset is already around 1GB in size, so I presume DiffuSeq has the ability the scale to large datasets. Can I ask why you guys haven't included such pretraining experiments?

Thank you!

**Comment by summmeer** [comment]
Hi, 
Honestly, the training cost is our biggest concern.
