### ISSUE TITLE
Problem about Commonsense Conversation Dataset

### ISSUE THREAD

**Issue by Kite0011** [Shark-NLP/DiffuSeq#7]
Thanks for your great job!

In your repo i found the dataset sample CommonsenseConversation, but when i try downloading it i found i can't get it down in the link: http://coai.cs.tsinghua.edu.cn/hml/dataset/#commonsense

I'm curious how you can access this dataset, I would be very honored if you could answer my question!

**Comment by summmeer** [comment]
It seems that their link has been moved somewhere else. You can use the google drive link we prepared.
