### ISSUE TITLE
ddim sampling

### ISSUE THREAD

**Issue by BIT-MJY** [Shark-NLP/DiffuSeq#78]
Hi @summmeer ,

Thanks for your great work! I just wonder whether I can directly replace the p_sample() function with ddim_sample() function in your code while keeping any other thing fixed (e.g., same training process)?

Looking forward to your reply!

**Comment by summmeer** [comment]
Yes, you can do that, but we suggest you to use our DiffuSeq-v2 ([Paper](https://arxiv.org/abs/2310.05793), [Code](https://github.com/Shark-NLP/DiffuSeq/tree/diffuseq-v2)) which uses [dpm-solver](https://github.com/LuChengTHU/dpm-solver) and performs better than DDIM.

**Comment by BIT-MJY** [comment]
thanks for the answer!
