### ISSUE TITLE
Pretrained checkpoint for QG

### ISSUE THREAD

**Issue by gkebe** [Shark-NLP/DiffuSeq#9]
Hi,

Thank you for sharing your amazing work. The repository is very clean and the instructions are easy to follow.
I see that you have recently uploaded the pretrained checkpoint for QQP. Would it be possible to obtain the pretrained checkpoint for the Quasar-T dataset too?

Thank you!

**Comment by summmeer** [comment]
Hi, [link](https://drive.google.com/drive/folders/1lHPp-T-ytp-YVptiokeYK-Lth48EGQ12?usp=sharing) is updated
